### ISSUE TITLE
Visualization problem

### ISSUE THREAD

**Issue by YuHang-max** [Xinwei-Wei/SR-MT3#1]
Hello, thank you for your code support! When I am testing, set matFile="result1" to get result1.file , how to visualize it? Hope to get your guidance

**Comment by YuHang-max** [comment]
Aaargh! I seem to have figured it out! I'll try.

**Comment by Xinwei-Wei** [comment]
Sorry, I am participating in a conference abroad. The result file is a .mat file which can be imported to and analyzed in MATLAB. 
You could try to analyze it in MATLAB first, and if it doesn't work either, I will send you a demo for visualization written in MATLAB as soon as I return. 
Thank you for supporting our work!
